export interface CurrencyName {
  code: string;
  name: string;
}

export const currencyNames: { [key: string]: string } = {
  // Major Fiat Currencies
  USD: 'US Dollar',
  EUR: 'Euro',
  GBP: 'British Pound',
  JPY: 'Japanese Yen',
  AUD: 'Australian Dollar',
  CAD: 'Canadian Dollar',
  CHF: 'Swiss Franc',
  CNY: 'Chinese Yuan',
  INR: 'Indian Rupee',
  BRL: 'Brazilian Real',
  RUB: 'Russian Ruble',
  KRW: 'South Korean Won',
  SGD: 'Singapore Dollar',
  NZD: 'New Zealand Dollar',
  MXN: 'Mexican Peso',
  HKD: 'Hong Kong Dollar',
  TRY: 'Turkish Lira',
  SAR: 'Saudi Riyal',
  AED: 'UAE Dirham',
  SEK: 'Swedish Krona',
  NOK: 'Norwegian Krone',
  DKK: 'Danish Krone',
  PLN: 'Polish Złoty',
  THB: 'Thai Baht',
  ZAR: 'South African Rand',
  
  // Asian Currencies
  IDR: 'Indonesian Rupiah',
  MYR: 'Malaysian Ringgit',
  PHP: 'Philippine Peso',
  TWD: 'Taiwan Dollar',
  VND: 'Vietnamese Dong',
  BDT: 'Bangladeshi Taka',
  PKR: 'Pakistani Rupee',
  LKR: 'Sri Lankan Rupee',
  NPR: 'Nepalese Rupee',
  MVR: 'Maldivian Rufiyaa',
  BND: 'Brunei Dollar',
  KHR: 'Cambodian Riel',
  LAK: 'Laotian Kip',
  MOP: 'Macanese Pataca',
  
  // Middle Eastern Currencies
  ILS: 'Israeli New Shekel',
  KWD: 'Kuwaiti Dinar',
  QAR: 'Qatari Riyal',
  BHD: 'Bahraini Dinar',
  OMR: 'Omani Rial',
  JOD: 'Jordanian Dinar',
  
  // African Currencies
  EGP: 'Egyptian Pound',
  KES: 'Kenyan Shilling',
  NGN: 'Nigerian Naira',
  DZD: 'Algerian Dinar',
  MAD: 'Moroccan Dirham',
  TND: 'Tunisian Dinar',
  MUR: 'Mauritian Rupee',
  SCR: 'Seychellois Rupee',
  XAF: 'Central African CFA Franc',
  XOF: 'West African CFA Franc',
  
  // European Currencies
  CZK: 'Czech Koruna',
  HUF: 'Hungarian Forint',
  RON: 'Romanian Leu',
  HRK: 'Croatian Kuna',
  ISK: 'Icelandic Króna',
  UAH: 'Ukrainian Hryvnia',
  
  // Latin American Currencies
  CLP: 'Chilean Peso',
  ARS: 'Argentine Peso',
  COP: 'Colombian Peso',
  PEN: 'Peruvian Sol',
  BOB: 'Bolivian Boliviano',
  UYU: 'Uruguayan Peso',
  CRC: 'Costa Rican Colón',
  GTQ: 'Guatemalan Quetzal',
  PAB: 'Panamanian Balboa',
  PYG: 'Paraguayan Guaraní',
  
  // Central Asian Currencies
  UZS: 'Uzbekistani Som',
  KZT: 'Kazakhstani Tenge',
  AZN: 'Azerbaijani Manat',
  GEL: 'Georgian Lari',
  AMD: 'Armenian Dram',
  KGS: 'Kyrgystani Som',
  TJS: 'Tajikistani Somoni',
  TMT: 'Turkmenistani Manat',
  MNT: 'Mongolian Tugrik',
  
  // Stablecoins
  USDT: 'Tether',
  USDC: 'USD Coin',
  DAI: 'Dai',
  BUSD: 'Binance USD',
  TUSD: 'TrueUSD',
  USDP: 'Pax Dollar',
  GUSD: 'Gemini Dollar',
  HUSD: 'HUSD',
  SUSD: 'sUSD',
  EURS: 'STASIS EURO',
  EURT: 'Tether EUR',
  GBPT: 'Tether GBP',
  
  // Major Cryptocurrencies
  BTC: 'Bitcoin',
  ETH: 'Ethereum',
  BNB: 'Binance Coin',
  SOL: 'Solana',
  ADA: 'Cardano',
  DOT: 'Polkadot',
  DOGE: 'Dogecoin',
  AVAX: 'Avalanche',
  MATIC: 'Polygon',
  LINK: 'Chainlink',
  UNI: 'Uniswap',
  AAVE: 'Aave',
  ALGO: 'Algorand',
  ATOM: 'Cosmos',
  XRP: 'Ripple',
  LTC: 'Litecoin',
  XMR: 'Monero',
  DASH: 'Dash',
  ZEC: 'Zcash',
  EOS: 'EOS',
  TRX: 'TRON',
  XLM: 'Stellar',
  VET: 'VeChain',
  THETA: 'Theta Token',
  FIL: 'Filecoin',
  ICP: 'Internet Computer',
  NEAR: 'NEAR Protocol',
  FTM: 'Fantom',
  
  // Gaming & Metaverse Tokens
  MANA: 'Decentraland',
  SAND: 'The Sandbox',
  AXS: 'Axie Infinity',
  ENJ: 'Enjin Coin',
  GALA: 'Gala',
  CHZ: 'Chiliz',
  
  // DeFi Tokens
  BAT: 'Basic Attention Token',
  COMP: 'Compound',
  MKR: 'Maker',
  SNX: 'Synthetix',
  YFI: 'yearn.finance',
  SUSHI: 'SushiSwap',
  CAKE: 'PancakeSwap',
  CRV: 'Curve DAO Token',
  BAL: 'Balancer',
  REN: 'Ren',
  OCEAN: 'Ocean Protocol',
  BAND: 'Band Protocol',
  
  // Other Notable Cryptocurrencies
  KSM: 'Kusama',
  WAVES: 'Waves',
  QTUM: 'Qtum',
  NEO: 'NEO',
  IOTA: 'IOTA',
  NANO: 'Nano',
  ONE: 'Harmony',
  ZIL: 'Zilliqa',
  ICX: 'ICON',
  ONT: 'Ontology',
  VGX: 'Voyager Token',
  CELO: 'Celo',
  CKB: 'Nervos Network',
  SKL: 'Skale Network',
  OXT: 'Orchid',
  RENBTC: 'renBTC',
  WBTC: 'Wrapped Bitcoin',
  PAXG: 'PAX Gold',
  
  // Special Drawing Rights and Regional Currencies
  XDR: 'Special Drawing Rights',
  XPF: 'CFP Franc',
  XCD: 'East Caribbean Dollar'
};

export const getCurrencyName = (code: string): string => {
  return currencyNames[code] || code;
}; 